version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:00"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "chore"
    labels:
      - "priority: low"
      - "scope: cargo"
      - "scope: dependency"
      - "status: new"
      - "type: chore"
    open-pull-requests-limit: 20
    target-branch: "deps"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:00"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "chore"
    labels:
      - "priority: low"
      - "scope: dependency"
      - "scope: github-action"
      - "status: new"
      - "type: chore"
    open-pull-requests-limit: 10
    target-branch: "deps"
