[package]
name = "svarozhits"
version = "0.1.0"
authors = ["raroh73"]
edition = "2021"
readme = "README.md"
repository = "https://github.com/raroh73/svarozhits"
license = "MIT"

[dependencies]
axum = "0.5.17"
serde = { version = "1.0.145", features = ["derive"] }
sqlx = { version = "0.6.2", features = [
    "offline",
    "runtime-tokio-rustls",
    "sqlite",
] }
tokio = { version = "1.21.2", features = [
    "macros",
    "rt-multi-thread",
    "signal",
] }
tower-http = { version = "0.3.0", features = ["trace"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
