name: Automatic Rebase
on:
  push:
    branches:
      - main
jobs:
  rebase:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: deps
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git rebase origin/main
          git push origin deps --force-with-lease
