name: CI/CD
on:
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Nix
        uses: cachix/install-nix-action@v17
      - name: Setup Cachix
        uses: cachix/cachix-action@v10
        with:
          name: svarozhits
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          extraPullNames: nix-community, pre-commit-hooks
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Do checks
        run: nix flake check
      - name: Build images
        run: |
          nix build \
            .#docker-image-amd64 \
            .#docker-image-arm64
          ls -1 result* | xargs --no-run-if-empty -L 1 docker image load -i
      - name: Rename images
        run: |
          docker image tag ghcr.io/raroh73/svarozhits:amd64 \
            ghcr.io/raroh73/svarozhits:latest-amd64
          docker image tag ghcr.io/raroh73/svarozhits:arm64 \
            ghcr.io/raroh73/svarozhits:latest-arm64
          docker image rm \
            ghcr.io/raroh73/svarozhits:amd64 \
            ghcr.io/raroh73/svarozhits:arm64
      - name: Push images
        run: docker image push --all-tags ghcr.io/raroh73/svarozhits
      - name: Push manifest
        run: |
          docker manifest create ghcr.io/raroh73/svarozhits:latest \
            --amend ghcr.io/raroh73/svarozhits:latest-amd64 \
            --amend ghcr.io/raroh73/svarozhits:latest-arm64
          docker manifest push ghcr.io/raroh73/svarozhits:latest
