name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Nix
        uses: cachix/install-nix-action@v17

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          nix build .#docker-image-arm64
          docker load < result

      - name: Push image
        run: docker push raroh73/svarozhits:latest
