name: Build and push docker images
on:
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Nix
        uses: cachix/install-nix-action@v18
      - name: Setup Cachix
        uses: cachix/cachix-action@v11
        with:
          name: svarozhits
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build images
        run: |
          nix build \
            .#docker-image-linux-amd64 \
            .#docker-image-linux-arm64
          ls -1 result* | xargs --no-run-if-empty -L 1 docker image load -i
      - name: Rename images
        run: |
          docker image tag ghcr.io/raroh73/svarozhits:linux-amd64 \
            ghcr.io/raroh73/svarozhits:latest-linux-amd64
          docker image tag ghcr.io/raroh73/svarozhits:linux-arm64 \
            ghcr.io/raroh73/svarozhits:latest-linux-arm64
          docker image rm \
            ghcr.io/raroh73/svarozhits:linux-amd64 \
            ghcr.io/raroh73/svarozhits:linux-arm64
      - name: Push images
        run: docker image push --all-tags ghcr.io/raroh73/svarozhits
      - name: Push manifest
        run: |
          docker manifest create ghcr.io/raroh73/svarozhits:latest \
            --amend ghcr.io/raroh73/svarozhits:latest-linux-amd64 \
            --amend ghcr.io/raroh73/svarozhits:latest-linux-arm64
          docker manifest push ghcr.io/raroh73/svarozhits:latest
