name: Check pull request
on:
  pull_request:
    branches:
      - main
jobs:
  checks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Nix
        uses: cachix/install-nix-action@v18
      - name: Do checks
        run: nix flake check
